filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/airflow/**/*.log
    fields:
      service: airflow
    fields_under_root: false
    multiline:
      pattern: '^\[?[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after

  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
